#!/usr/bin/env bash
# -f tells pgrep to match agains the full command line, xargs builds commands from input via stdin (-15 is optional), -r tells xargs to not run the command if stdin is empty
pgrep -f "4-to_infinity_and_beyond" | xargs -r kill -15
